spring:
  profiles:
    active: local
management:
  health:
    influxdb:
      enabled: true
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude:
        - env
        - bean

---
spring:
  profiles: local
  influx2: 
    url: http://localhost:9999
    username: donghoon
    password: vhrxks12
    token: Ct0GUP-9GDLjRjo8lihTMfUmd-fGaJNau2A6cMsUJm-qIaGBG6yFYti3CxkirKlBu79kZUdQHm39kDR8Y8YZIQ==
    org: khan
    bucket: demo-bucket
    logLevel: BODY
    readTimeout: 5s
    writeTimeout: 5s
    connectTimeout: 5s

server:
  port: 8080