spring:
  profiles:
    active: local
management:
  health:
    influxdb:
      enabled: true
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude:
        - env
        - bean

---
spring:
  profiles: local
  influx2: 
    url: http://localhost:9999
    username: donghoon
    password: password
    token: token
    org: khan
    bucket: demo-bucket
    logLevel: BODY
    readTimeout: 5s
    writeTimeout: 5s
    connectTimeout: 5s

server:
  port: 8080

---
spring:
  profiles: k8s
  influx2: 
    url: ${INFLUX2_URL}
    username: ${INFLUX2_USERNAME}
    password: ${INFLUX2_PASSWORD}
    token: ${INFLUX2_TOKEN}
    org: ${INFLUX2_ORG}
    bucket: ${INFLUX2_BUCKET}
    logLevel: BODY
    readTimeout: 5s
    writeTimeout: 5s
    connectTimeout: 5s

server:
  port: 8080